// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9kK2UHUkxTJ0N5kzhnttZJ1zRR9l9R2g',
    appId: '1:65078592075:web:6ac1865359a9e952b803ce',
    messagingSenderId: '65078592075',
    projectId: 'blue-bite-e8b42',
    authDomain: 'blue-bite-e8b42.firebaseapp.com',
    storageBucket: 'blue-bite-e8b42.firebasestorage.app',
    measurementId: 'G-512W25WM5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxVj6dFam1m3CvdDgU7p1usrcIKxK_2g',
    appId: '1:65078592075:android:405483dade47a1feb803ce',
    messagingSenderId: '65078592075',
    projectId: 'blue-bite-e8b42',
    storageBucket: 'blue-bite-e8b42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCz-0g6sjywnuIB2g8Q4j29OQVBq1dfN4',
    appId: '1:65078592075:ios:216d4142001e3b5cb803ce',
    messagingSenderId: '65078592075',
    projectId: 'blue-bite-e8b42',
    storageBucket: 'blue-bite-e8b42.firebasestorage.app',
    iosBundleId: 'com.example.restaurantManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCz-0g6sjywnuIB2g8Q4j29OQVBq1dfN4',
    appId: '1:65078592075:ios:216d4142001e3b5cb803ce',
    messagingSenderId: '65078592075',
    projectId: 'blue-bite-e8b42',
    storageBucket: 'blue-bite-e8b42.firebasestorage.app',
    iosBundleId: 'com.example.restaurantManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9kK2UHUkxTJ0N5kzhnttZJ1zRR9l9R2g',
    appId: '1:65078592075:web:55be743abc4d5962b803ce',
    messagingSenderId: '65078592075',
    projectId: 'blue-bite-e8b42',
    authDomain: 'blue-bite-e8b42.firebaseapp.com',
    storageBucket: 'blue-bite-e8b42.firebasestorage.app',
    measurementId: 'G-XEKJZPCL5J',
  );
}
